name: firebase_ml_vision_example
description: Demonstrates how to use the firebase_ml_vision plugin.
author: Flutter Team <flutter-dev@googlegroups.com>

dependencies:
  flutter:
    sdk: flutter

  image: 2.0.5
  firebase_ml_vision: 0.2.1
  camera: ^0.2.9
  firebase_core: ^0.2.5+1
  firebase_database: ^1.0.5

flutter:
  uses-material-design: true
